### ISSUE TITLE
Bateau en mer

### ISSUE THREAD

**Issue by maplepy** [MiMillieuh/Adobe-Lightroom-CC-Linux#3]
Comment est-ce que je pourrais faire pour avoir une licence type bateau en pleine mer pour ce logiciel shippe de cette facon?

**Comment by MiMillieuh** [comment]
Je sais pas ce qu'est la licence bateau en pleine mer mais tu peux acheter la licence sur le site officiel d'Adobe.

**Comment by maplepy** [comment]
justement, j'aimerais l'utiliser sans forcement de licence

**Comment by MiMillieuh** [comment]
Je ne fournirait jamais un moyen d'utiliser un logiciel sans les licences si il n'y a pas de raisons valides à cela.

Il y a toujours des alternatives libres et gratuites si vraiment.
